name = "Material Dark Theme"
version = "0.0.3"
authors = ["Xero <xeroday@duck.com>"]
description = "Theme that imitates Google's Material Dark theme."
repository = "https://github.com/xerodark/zed-material-theme"
id = "material-dark"
schema_version = 1
