name = "Material Dark Theme"
version = "0.0.2"
authors = ["Xero <xeroday@duck.com>"]
description = "Theme that immitates Google's Material Dark theme."
repository = "https://github.com/xerodark/zed-material-theme"
id = "material-dark-theme"
schema_version = 1
